# The URL the site will be built for
base_url = "https://sdragonex.github.io/Maturita"

# The site title and description.
title = "Maturita 2027"
description = "Studijní příprava · SŠTE Brno · Informační technologie"

generate_feeds = false
default_language = "cs"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = false

# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     author = "Famous author"
#
# author value will be available using {{ config.extra.author }} in templates
#

[markdown]
render_emoji = true
github_alerts = true
bottom_footnotes = true

[markdown.highlighting]
style = "class"
light_theme = "one-light"
dark_theme = "one-dark-pro"
extra_grammars = [ "syntaxes/math-display.json" ]

[extra]
main_section = "posts"
math_display = "mathjax"
avatar = ""
author = "Dany Chaker"

home_layout = "focus"
motto_mode = "multi"
home_recent_posts = 3

mottos = [
    "SŠTE Olomoucká",
    "Informační technologie",
]

social_links = [
    { name = "github", url = "https://github.com/SDragonex" }
]

[extra.sections]
posts  = true
about  = true
links  = true
