name = "Maturita"
description = "Kompletní příprava na Maturitní zkoušku"
tags = ["Clean", "Blog", "Responsive"]
license = "MIT"
homepage = "https://github.com/SDragonex/Maturita"
# The minimum version of Zola required
min_version = "0.21.0"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]
main_section = "posts"
home_layout = "focus"
motto_mode = "hide"
home_greeting = false
home_recent_posts = 0

[extra.sections]
posts = true
about = true
archive = true
tags = false
links = true

# The theme author info: you!
[author]
name = "Dany Chaker"
homepage = "https://sdragonex.github.io/Maturita/"
